### ISSUE TITLE
Sintesis-De-Calidad

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-javiern-778#1]
[sinstesis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-javiern-778/files/9700463/sinstesis.pdf)

**Comment by ArturoAngonJose** [comment]
calificacion: 20/20

**Comment by josealfredo79** [comment]
Esto esta incompleto...favor de realizarlo bien...

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
